#!/bin/bash

# --- My Personal Command Cheatsheet ---
# Add any commands or notes you tend to forget.

echo "--- GIT COMMANDS ---"
echo "  git pull                # Get latest changes"
echo "  git add .               # Stage all changes"
echo "  git commit -m 'message' # Commit with a message"
echo "  git push                # Send changes to remote"
echo ""
echo "--- ZIP A FOLDER ---"
echo "  zip -r archive_name.zip /path/to/folder"
echo ""
echo "--- CHECK DISK USAGE ---"
echo "  df -h"
echo ""
echo "--- HOMEBREW COMMANDS (macOS) ---"
echo "  brew update             # Update Homebrew"
echo "  brew upgrade            # Upgrade packages"
echo "  brew search <package>   # Search for packages"
echo "  brew install <package>  # Install package"
echo ""
echo "--- PYTHON VIRTUAL ENVIRONMENTS ---"
echo "  python3 -m venv venv    # Create virtual environment"
echo "  source venv/bin/activate # Activate environment"
echo "  pip install <package>   # Install package in venv"
echo "  deactivate              # Exit virtual environment"
echo ""
echo "--- USEFUL macOS SHORTCUTS ---"
echo "  open .                  # Open current directory in Finder"
echo "  pbcopy < file.txt       # Copy file contents to clipboard"
echo "  pbpaste > file.txt      # Paste clipboard to file"
echo "  mdfind 'search term'    # Spotlight search from terminal"

echo ""
echo "--- DAILY CONTEXT SYSTEM ---"
echo "  startday                # Morning routine (auto-runs once/day)"
echo "  status                  # Show current context dashboard"
echo "  goodevening             # Run end-of-day summary"
echo "  journal 'message'       # Add a journal entry"
echo "  todo add 'task'         # Add a to-do item"
echo "  todo list               # Show current tasks"
echo "  todo done <num>         # Mark task as complete"
echo "  health add 'desc' 'YYYY-MM-DD HH:MM'  # Add appointment"
echo "  health list             # Show upcoming appointments"
echo "  weekreview              # Show last 7 days activity"
echo "  graballtext             # Dump all readable text into all_text_contents.txt"
echo "  projects forgotten      # List old projects"
echo "  projects recall <name>  # Show details of an old project"
echo "  blog status             # Show blog status"
echo "  blog stubs              # List blog posts that are stubs"
echo ""
echo "--- AI STAFF HQ DISPATCHERS (10 Available) ---"
echo "  Technical:"
echo "    cat script.sh | tech         # Debug code"
echo "  "
echo "  Creative:"
echo "    creative 'story'             # Story package"
echo "    narrative 'plot' | narrative # Plot structure"
echo "    copy 'product' | copy        # Sales copy"
echo "  "
echo "  Strategy & Analysis:"
echo "    <input> | strategy           # Strategic analysis"
echo "    <input> | brand              # Brand positioning"
echo "    <input> | market             # Market research"
echo "  "
echo "  Personal Development:"
echo "    <challenge> | stoic          # Stoic coaching"
echo "    <research> | research        # Knowledge synthesis"
echo ""
echo "  Workflow integrations:"
echo "  blog generate <stub>           # AI-generate content from stub"
echo "  blog refine <file>             # AI-polish existing content"
echo "  todo debug <num>               # AI-debug a task"
echo "  todo delegate <num> <type>     # Delegate to AI specialist"
echo "  journal analyze                # AI insights (7 days)"
echo "  journal mood                   # AI sentiment analysis (14 days)"
echo "  journal themes                 # AI theme extraction (30 days)"
echo ""
echo "  Setup: cp .env.example .env && add your OPENROUTER_API_KEY"
echo "  Docs: ~/dotfiles/bin/README.md or ~/dotfiles/ROADMAP.md"
echo ""
echo "--- DATA LOCATION ---"
echo "  All data stored in: ~/.config/dotfiles-data/"
echo "  - journal.txt, todo.txt, todo_done.txt, health.txt"
echo "  - dir_bookmarks, dir_history, favorite_apps"
echo ""
echo "--- NEED HELP? ---"
echo "  Read the Daily Happy Path Guide:"
echo "  cat ~/dotfiles/docs/happy-path.md"
echo "  (Step-by-step workflow for brain fog days)"
