#!/bin/bash

# --- My Personal Command Cheatsheet ---
# Add any commands or notes you tend to forget.

echo "--- GIT COMMANDS ---"
echo "  git pull                # Get latest changes"
echo "  git add .               # Stage all changes"
echo "  git commit -m 'message' # Commit with a message"
echo "  git push                # Send changes to remote"
echo ""
echo "--- ZIP A FOLDER ---"
echo "  zip -r archive_name.zip /path/to/folder"
echo ""
echo "--- CHECK DISK USAGE ---"
echo "  df -h"
echo ""
echo "--- HOMEBREW COMMANDS (macOS) ---"
echo "  brew update             # Update Homebrew"
echo "  brew upgrade            # Upgrade packages"
echo "  brew search <package>   # Search for packages"
echo "  brew install <package>  # Install package"
echo ""
echo "--- PYTHON VIRTUAL ENVIRONMENTS ---"
echo "  python3 -m venv venv    # Create virtual environment"
echo "  source venv/bin/activate # Activate environment"
echo "  pip install <package>   # Install package in venv"
echo "  deactivate              # Exit virtual environment"
echo ""
echo "--- USEFUL macOS SHORTCUTS ---"
echo "  open .                  # Open current directory in Finder"
echo "  pbcopy < file.txt       # Copy file contents to clipboard"
echo "  pbpaste > file.txt      # Paste clipboard to file"
echo "  mdfind 'search term'    # Spotlight search from terminal"

echo ""
echo "--- DAILY CONTEXT SYSTEM ---"
echo "  status                  # Show current context dashboard"
echo "  journal 'message'       # Add a journal entry"
echo "  todo add 'task'         # Add a to-do item"
echo "  goodevening             # Run end-of-day summary"
echo "  projects forgotten      # List old projects"
echo "  projects recall <name>  # Show details of an old project"
echo "  blog status             # Show blog status"
echo "  blog stubs              # List blog posts that are stubs"